# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  workflow_dispatch:
 

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2  
 
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gopinath003/docker-image-autobuild:latest 
      - name: push the docker image
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}} && docker push gopinath003/docker-image-autobuild:latest

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # The email address associated with your Heroku account.     
          email: ${{ secrets.HEROKU_EMAIL }}          
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          
      # Build Docker image
      - name: Docker build
        run: docker login --${{secrets.DOCKER_USER}}=_ --${{secrets.DOCKER_TOKEN}}=$heroku_api_key registry.heroku.com
      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $heroku_app_name
          heroku container:release web -a $heroku_app_name

        
          #Heroku Container Login
          #heroku container: login
          
          #Push the Docker imag to Heroku Container
          #heroku container push: heroku push gopinath003/docker-image-autobuild:latest
          
          #heroku container release: release gopinath003/docker-image-autobuild:latest 
